name: narojay.blog
on: 
 push:
  branches: [master]
 pull_request:
  branches: [master]
env:
    IMAGE_NAME: narojay/blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Set selected color
          run: | 
                 TAG=$(date +%y%m%d%H%M%S)
                 echo '::set-output name=SELECTED_COLOR::${TAG}'
          id: random-color-generator
        - name: Get color
          run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
        - name: Get color
          run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
   
