name: narojay.blog
on: 
 push:
  branches: [master]
 pull_request:
  branches: [master]
env:
    IMAGE_NAME: narojay/blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - run: echo $(date +%y%m%d%H%M%S)
        - run: echo $(date +%y%m%d%H%M%S)
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build and push Docker images
#         uses: docker/build-push-action@v3.0.0
#         with:
#          push: true
#          file: ./src/Narojay.Blog/Dockerfile
#          tags:  ${{ env.IMAGE_NAME }}:${{ IMAGE_TAG }}
   
