name: narojay.blog
on: 
 push:
  branches: [master]
 pull_request:
  branches: [master]
env:
    IMAGE_NAME: narojay/blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: tag generate
          id: t1
          uses: Kaven-Universe/github-action-current-date-time@v1.1.0
          with:
            format: "MMDDHHmmss"
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push Docker images
          uses: docker/build-push-action@v3.0.0
          with:
           push: true
           file: ./src/Narojay.Blog/Dockerfile
           tags:  ${{ env.IMAGE_NAME }}:${{ steps.t1.outputs.time }}
        - name: start application
          uses: garygrossgarten/github-action-ssh@v0.6.3
          with:
           command: bash /www/wwwroot/command/narojayapi.sh ${{ steps.t1.outputs.time }}
           host: ${{ secrets.Host }}
           username: ${{ secrets.UserName }}
           privateKey: ${{ secrets.Password }}
       
