name: narojay.blog
on: 
 push:
  branches: [master]
 pull_request:
  branches: [master]
env:
    IMAGE_NAME: narojay/narojay.blog.api
    IMAGE_TAG: demo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
         push: true
         tags: blog:1
   
