name: narojay.blog
on: 
 push:
  branches: [master]
 pull_request:
  branches: [master]
env:
    IMAGE_NAME: narojay/narojay.blog.api
    IMAGE_TAG: demo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: 6.0.202
     - name: dotnet restore #还原包
       run: dotnet restore ./src/Narojay.Blog
     - name: dotnet publish #发布项目
       run: dotnet publish ./src/Narojay.Blog --configuration -c Release --no-restore -o app  
     - name: test
       run: echo ${{ steps.meta.outputs.tags }}
